# Path to your oh-my-zsh installation.
export ZSH=$HOME/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="half-life"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

# User configuration

  export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:$PATH"
# export MANPATH="/usr/local/man:$MANPATH"
export EDITOR="vim"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias aui="sudo apt-get update; sudo apt-get upgrade; sudo apt-get dist-upgrade"
#alias agu="sudo apt-get update" # obsoleted by debian plugin
#alias agi="sudo apt-get install" # obsoleted by debian plugin
alias kb="keybase"
alias gpg="gpg2"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
## Antigen
# Source antigen
source ~/.antigen.zsh
# Make sure oh-my-zsh works on most/all device
antigen use oh-my-zsh
# Plugins
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle brew
antigen bundle bundler
antigen bundle catimg
#antigen bundle chucknorris
antigen bundle command-not-found
antigen bundle cloudapp
antigen bundle common-aliases
antigen bundle debian
antigen bundle dircycle
antigen bundle dirhistory
antigen bundle docker
antigen bundle encode64
#antigen bundle geeknote
antigen bundle git-extras
#antigen bundle lol
antigen bundle npm
antigen bundle nyan
antigen bundle pip
antigen bundle pylint
antigen bundle python
antigen bundle redis-cli
antigen bundle ruby
antigen bundle rvm
antigen bundle screen
antigen bundle sprunge
antigen bundle sudo
antigen bundle vagrant
antigen bundle wd

antigen theme half-life
### Bashhub.com Installation
if [ -f ~/.bashhub/bashhub.zsh ]; then
    source ~/.bashhub/bashhub.zsh
fi

# Golang support
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

######## Generated by Betty's install script
alias betty='/home/ubuntu/betty/main.rb'

# Add support for nvbn/thefuck
eval "$(thefuck --alias)"

# Java home
export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/jre"
export PATH="$JAVA_HOME/bin:$PATH"

# Gets rid of pain-in-the-butt .zcompdumps
#rm -r .zcompdump*
